name : shell commands

on : [push]

jobs:
  run-shell-commands:
    runs-on : ubuntu-latest
    steps:
      - name: display a string
        run: echro "hello world"
      - name: multi line string
        run: |
          node -v
          npm -v

